apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: api-error-rate
  namespace: demo
spec:
  metrics:
    - name: api-error-rate
      interval: 15s
      count: 4
      failureLimit: 1
      successCondition: result[0] < 0.05
      failureCondition: result[0] > 0.10
      provider:
        prometheus:
          address: http://kube-prometheus-stack-prometheus.monitoring.svc:9090
          query: |
            sum(rate(flask_http_request_total{namespace="demo",job="api",status=~"5.."}[1m]))
            /
            clamp_min(sum(rate(flask_http_request_total{namespace="demo",job="api"}[1m])), 0.001)
