apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api
  namespace: monitoring
  labels:
    app: api
spec:
  namespaceSelector:
    matchNames:
      - demo
  selector:
    matchLabels:
      app: api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
      relabelings:
        - sourceLabels:
            - __meta_kubernetes_pod_label_rollouts_pod_template_hash
          targetLabel: rollout_revision
