apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 65.1.1
    helm:
      values: |
        alertmanager:
          alertmanagerSpec:
            secrets:
              - alertmanager-gmail-secret

          config:
            global:
              resolve_timeout: 1m
              smtp_smarthost: smtp.gmail.com:587
              smtp_from: vietpno3@gmail.com
              smtp_auth_username: vietpno3@gmail.com
              smtp_auth_password_file: /etc/alertmanager/secrets/alertmanager-gmail-secret/smtp-auth-password
              smtp_require_tls: true

            route:
              receiver: "null"
              group_by: ["alertname", "service"]
              group_wait: 10s
              group_interval: 30s
              repeat_interval: 5m
              routes:
                - receiver: email-personal
                  matchers:
                    - alertname="ApiHighErrorRate"

            receivers:
              - name: "null"
              - name: email-personal
                email_configs:
                  - to: nampno3@gmail.com
                    send_resolved: true
        prometheus:
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
            ruleSelectorNilUsesHelmValues: false
        grafana:
          adminPassword: admin123
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
